### ISSUE TITLE
USER STORY: Django/Libraries Install

### ISSUE THREAD

**Issue by seanf316** [seanf316/P4-Cinema-Go#11]
As a **Developer** I can **set up Django and install the supporting libraries predicted to be needed** so that **I am ready to start development**

## Acceptance Criteria
- Django installed and Django success page displayed when running server
- Libraries installed and added to requirements.txt

## Tasks
- [x] Task 1 - Install Django and Gunicorn
- [x] Task 2 - dj_database_url psycopg2
- [x] Task 3 - dj3-cloudinary-storage
- [x] Task 4 - django-summernote
- [x] Task 5 - Create a requirements.txt file
- [x] Task 6 - Create project Cinema-Go

**Comment by seanf316** [comment]
Django has been setup along with libraries required for the project.  Commit - [16691c9](https://github.com/seanf316/P4-Cinema-Go/commit/16691c9f5c76c4fc9f59f9ad4ce7b37fc635d1f9)

**Comment by seanf316** [comment]
Summernote was removed due to toolbar not working well within crispy forms, Richtextfield installed - e0d9fc68998fbf4e6e49efae9aa43bd240dc833d

**Comment by seanf316** [comment]
All files edited to remove Summernote and apply Richtextfield where required - 20cbf4819717f78c8e2c6ab19c352ee657846767
