### ISSUE TITLE
USER STORY: Early Deployment to Heroku

### ISSUE THREAD

**Issue by seanf316** [seanf316/P4-Cinema-Go#13]
As a **Developer** I can **deploy site to Heroku early** so that **I can confirm everything works before development of the site and to enable continuous testing within the production environment**

## Acceptance Criteria
- Heroku config vars updated
- Github automatic deploys selected
- App deploys and launches without issue

## Tasks
- [x] Task 1 - Create a new Heroku App
- [x] Task 2 - Add the database to the app resources
- [x] Task 3 - Add the secret key’s to the Heroku config vars
- [x] Task 4 - Link to Github for automatic deployment
- [x] Task 5 - Configure the settings.py file to point at the correct env.py file in development, the os in deployment and adjust the database section to point at the correct database url from Heroku.

**Comment by seanf316** [comment]
App has been created and is launching as expected. Had to undo a typo in Procfile and also needed to updated ALLOWED_HOSTS with app name - https://github.com/seanf316/P4-Cinema-Go/commit/124351cd03a6758c3f34ee0c7ea0885f426f0486

**Comment by seanf316** [comment]
Tested some hero images with the cloudinary storage, also configured the settings.py to point at the correct env.py file in development within this commit - 4c705816c99dbe385593b017d51fa693ca0c15b9
