### ISSUE TITLE
USER STORY: Make Site Responsive on Multiple Devices

### ISSUE THREAD

**Issue by seanf316** [seanf316/P4-Cinema-Go#14]
As a **User** I would like **to view the site on my different devices** so that **I can view the site on the go**

## Acceptance Criteria
- SIte built to be responsive on multiple devices for a good User experience using Bootstrap
- Media Queries used to adjust css where needed

## Tasks
- [x] Task 1 - Install Bootstrap
- [x] Task 2 - Design Base Html using Bootstrap
- [x] Task 3 - Design index.html using Bootstrap

**Comment by seanf316** [comment]
Bootstrap was installed and Base.html was created. Some styling and testing was done within this commit - 4c705816c99dbe385593b017d51fa693ca0c15b9

Index.html was created in the commit mentioned above.

Further changes will be made so keeping at In-Progress for now.

**Comment by seanf316** [comment]
Index.html template updated with content displayed for logged in user - 578f33158505b16a7d64757e5c7bca46715e0bb9

Updated anchor tags with flex-wrap flex-grow for mobile view - 4b70f596c41b291a0b3778239290a8c8033570c0
