### ISSUE TITLE
USER STORY: Responsive Navbar

### ISSUE THREAD

**Issue by seanf316** [seanf316/P4-Cinema-Go#15]
As a **User** I want **to see a clear way of navigating the site** so that **I can find the information relative to my needs**

## Acceptance Criteria
- Create a nice Navbar with relevant links to parts of the site
- Create a Hamburger menu for mobiles and smaller Tablets

## Tasks
- [x] Task 1 - Use Bootstrap to create the Navbar
- [x] Task 2 - Add relevant links for the site pages to the Navbar
- [x] Task 3 - Test responsive Navbar on Chrome Dev Tools
- [x] Task 4 - Adjust Navbar view for Logged In users i.e. Profile Link/Reviews

**Comment by seanf316** [comment]
Index.html was created and hero image added. Styling was done and the Navbar was styled and tested using Chrome Dev Tools - 725f5d97d20cff6130548266b0538ef02516c553

**Comment by seanf316** [comment]
Navbar updated now with Profile link - c31961a601a0ceba9c7c91981429248c3d927b7f

Review link will be added when created.

**Comment by seanf316** [comment]
Navbar active link reference updated as it wasnt working as expected - 5ecc81c64ebdb68d7e44adc287338d0c610e2f64

**Comment by seanf316** [comment]
Navbar updated with Reviews link - 6268ca11f0387794f6cb9b707fbe6ac0c2d66844
