### ISSUE TITLE
USER STORY: Responsive Footer

### ISSUE THREAD

**Issue by seanf316** [seanf316/P4-Cinema-Go#16]
As a **User** I want **to be able to get in touch with the Developer** so that **I can enquire about issues/suggestions I may have**

## Acceptance Criteria
- Responsive Footer created for multiple Devices
- Social Links implemented
- Copyright implemented

## Tasks
- [x] Task 1 - Create Footer using Bootstrap
- [x] Task 2 - Implement Social links using Font Awesome Icons
- [x] Task 3 - Make sure all Social links open in a new tab
- [x] Task 4 - Add Copyright information

**Comment by seanf316** [comment]
Footer created and styled inline with site theme. Social links implemented and copyright added - e81e975b7a6ae772a38068e9569ab0ab0b018685

**Comment by seanf316** [comment]
Correct Github repo fixed in footer - 38d0a9af44e972f26c83a719298e9478e5b839fe
