### ISSUE TITLE
USER STORY: Sign Up/Login/Logout

### ISSUE THREAD

**Issue by seanf316** [seanf316/P4-Cinema-Go#17]
As a **User** I want to **Sign Up/Login and Logout** so that **I can see what features are available to registered users like reviewing/commenting**

## Acceptance Criteria
- Users are able to Sign Up
- Registered Users are able to Login/Logout

## Tasks
- [x] Task 1 - Install Allauth
- [x] Task 2 - Style pages to match site theme
- [x] Task 3 - Alter Navbar so relevant views are displayed to registered Users

**Comment by seanf316** [comment]
Installed Allauth and adjusted Navbar links to reflect the changes for registered users - f4ce78c2412ac1a66c25e430fe38522186dcbd1d

User story will be kept in progress until all pages have been styled.

**Comment by seanf316** [comment]
Installed crispy forms for Allauth pages and styled the allauth pages inline with site theme. I adjusted message text for logout and added toast functionality. More styling was applied throughout to make the pages more responsive. - 78c8dd597628e08f62fa070d359d746a643a73a3

More changes will be applied to restrict views of future pages to registered Users only.

**Comment by seanf316** [comment]
On further viewing of allauth django docs I have added some more settings for allauth signup/login - 91976f2273a8df181fdac3a5b843354a4d12ec9e
