### ISSUE TITLE
USER STORY: User Profile

### ISSUE THREAD

**Issue by seanf316** [seanf316/P4-Cinema-Go#18]
As a **User** I would **like access to my Profile** so that **I can upload an image or alter my details where needed**

## Acceptance Criteria
- User can access Profile and can Create/Read/Update/Delete their personal details

## Tasks
- [x] Task 1 - Create the model for the Profile
- [x] Task 2 - Write the view code for the Profile page
- [x] Task 3 - Add CRUD functionality to the view code

**Comment by seanf316** [comment]
Profiles app created - 7fa195b76311b6df4da586c2d1dba11ffc0fb0f3

**Comment by seanf316** [comment]
Profile model created and registered in admins.py. App updated in cinemago settings.py - fe00c403311b021b19cf5f659cbbea2d17400f76

**Comment by seanf316** [comment]
Changed Profile model variables to lowercase for easier readability and template update - 12be2f0bf6024bea818384279cd5da30be466e9b

**Comment by seanf316** [comment]
Updated Profiles urls.py with current paths - 58bf6d8d046a444251fb35754f4733e34ab829e3

**Comment by seanf316** [comment]
Profiles admin.py updated to reflect variable lowercase change - 556a97999c55fcfcc676a7f89a01e05d4b584186

**Comment by seanf316** [comment]
profile view created - f9589d5a8244c22df774df33dd4038f7621624e3

**Comment by seanf316** [comment]
signals.py created and code written for auto Profile creation when user signs up - c243938fb762e123ec7d1bbd21405425483cfc89

**Comment by seanf316** [comment]
Profiles apps.py updated to import profiles.signals - 89b24850587475325a79207d57ef7a38feca3516

**Comment by seanf316** [comment]
Cloudinary Image field updated to automatically format images to certain size and webp - 9b3b408ea4ed52310c03c9281a77565b8b16132a

**Comment by seanf316** [comment]
Profile model updated with fav_movie & director fields - e448b12da8714060a08949f455eea228b3ff4b9c

**Comment by seanf316** [comment]
Profile modal updated with to_watch field - 6e482c4335708b6122ffaa7f35d757558bf35d98

**Comment by seanf316** [comment]
Profile edit view created in this commit - 4a548be299f0d69290c734d099b358d3d7938627

**Comment by seanf316** [comment]
Profile urls updated with edit view path - a3f70d56bea33ed46cbe024174e2ca221fd85ddd

**Comment by seanf316** [comment]
Profile delete view created in this commit - 1f61f37dedecd455e18b4da09e437a75983ad832

**Comment by seanf316** [comment]
Profile urls updated with delete view path - 8c2614968097d3bd4a4e8611dd51ea9ba42d9b5a

**Comment by seanf316** [comment]
Profile model updated with reviewed field - 4632df2824f218498bf3890142690faee6985760

**Comment by seanf316** [comment]
Added some defensive programming to Profile views - 9fb123d1b281f5313c2fe7ac1f4d6568730ccbac

**Comment by seanf316** [comment]
Added placeholders for Profile fields - 3405fef0c9512869a268288019aa9e28d7e9f527

**Comment by seanf316** [comment]
Profile view updated to allow other users to view it - 6b36df8045c41a156d216e8cf568656df68eb2bc

**Comment by seanf316** [comment]
After profile template was updated to check if user is profile user unnecessary code removed from  prof_watch & prof_review views - aa49b9d29949026d3b3496efd6f025fe3aededd4

**Comment by seanf316** [comment]
Profile model updated with Favourite actor - 8dd3430b27112c31cf8fca3ea29ca09a3f28e985

**Comment by seanf316** [comment]
Profile form updated with email field - 5407e5a1fd3ca86bb9f5e9603a1e48a34cd7a76e

**Comment by seanf316** [comment]
Profile about field updated to a Richtextfield - fec1c8ef3b89c87286c1df6296c2ad2ecbdfd562

**Comment by seanf316** [comment]
prof_review view and profile template updated to point to edit_review page based off user feedback - 35b72d624009285e57834a4563d2c3b592b04fc0
