### ISSUE TITLE
USER STORY: Movie Search Template

### ISSUE THREAD

**Issue by seanf316** [seanf316/P4-Cinema-Go#20]
As a **Developer** I can **create the Movie Search Template** so that **the User has an nice experience on the site**

## Acceptance Criteria
- Create a responsive template that allows the user to quickly search for a specific Movie

## Tasks
- [x] Task 1 - Create Movie Search Template and extend from Base.html
- [x] Task 2 - Style Template to match site theme
- [x] Task 3 - Link in view code
- [x] Task 4 - Update URL's if required

**Comment by seanf316** [comment]
Movie Search Template created and extended from Base.html. It was linked using the view code and urls.py was updated. - 451290ae3f86c27ed96f43bb19af5ee074eeab66

Styling is on-going.

**Comment by seanf316** [comment]
More styling applied and content added - 578f33158505b16a7d64757e5c7bca46715e0bb9
