### ISSUE TITLE
USER STORY: API Sign Up

### ISSUE THREAD

**Issue by seanf316** [seanf316/P4-Cinema-Go#21]
As a **Developer** I need to **setup an account with TMDB** so that **I can use the sites API and implement into my site**

## Acceptance Criteria
- Sign up to TMDB and retrieve API Key

## Tasks
- [x] Task 1 - Create account with TMDB
- [x] Task 2 - Study API Documentation for the site
- [x] Task 3 - Retrieve API Key
- [x] Task 4 - Provide the get request to my view code

**Comment by seanf316** [comment]
TMDB account created and API Key retrieved. Requests to API working in the trending view - baeec66ce70c63eec909cba443bf914c96b844bd
