### ISSUE TITLE
USER STORY: Profile Template

### ISSUE THREAD

**Issue by seanf316** [seanf316/P4-Cinema-Go#23]
As a **Developer** I can **create an aesthetically pleasing display of the User's Profile** so that **the experience of viewing their Profile is a pleasant one**

## Acceptance Criteria
- When User clicks on their Profile a nice responsive display is shown

## Tasks
- [x] Task 1 - Create the Profile Page - extend from Base.html
- [x] Task 2 - Style the page to match site theme
- [x] Task 3 - Add "CTA" Buttons to allow for CRUD functionality

**Comment by seanf316** [comment]
profile.html created and extended from base.html - c7bc6bacb26951564ad868455dd92d97cc405e37

**Comment by seanf316** [comment]
profile.html styled to match site theme - 4e94d3c9cfe5b956d4f94a7665960359af8a3580

Further styling may be done

**Comment by seanf316** [comment]
edit_profile template created and styled - 2fdb96e1d2ce38360b572fb36c469f07de8d2c5e

**Comment by seanf316** [comment]
Edit cta button added to Profile template - 742819713601b9b2789f3ff04f9c1fd6265ff318

**Comment by seanf316** [comment]
Delete code added to edit profile template - de75558dc9bedb7dd2e60575ad639b11b7847d3e

**Comment by seanf316** [comment]
Review movie list added to Profile template - 576f347c992e569fee0b14a234ff53be501bb6e6

**Comment by seanf316** [comment]
Favourite actor field added, if statement implemented to check if user is profile owner - only then will the "Remove X" linked to prof_watch & prof_review be viewable to person viewing profile - bd54eebe072fe05e078aff827b782c257bca64cd

**Comment by seanf316** [comment]
Profile template updated with email field - 5407e5a1fd3ca86bb9f5e9603a1e48a34cd7a76e
