### ISSUE TITLE
USER STORY: Movie Details Template

### ISSUE THREAD

**Issue by seanf316** [seanf316/P4-Cinema-Go#24]
As a **Developer** I can **build a page to display the Movie Details for the users selected Movie** so that **they have a clear overview of the Movie**

## Acceptance Criteria
- When User selects the Movie from the search query they will land at a page that displays that Movie Detail

## Tasks
- [x] Task 1 - Create the Movie Details page - extend from Base.html
- [x] Task 2 - Style to match site theme
- [x] Task 3 - Update Urls if required

**Comment by seanf316** [comment]
Movie Details template has been created and Urls have been updated to reflect this - 48db8f5aeb7553d5d3cd1878057766a3dccaee02

User Story will stay in-progress until page fully styled inline with site theme.

**Comment by seanf316** [comment]
Further styling was applied to the Trending/Top Rated/Movie Details in this commit - 6edc5c6231a48a7ed90a1c73641d78de4c4bad36

**Comment by seanf316** [comment]
Updated the Movie Details template with "if" statements to avoid errors when api call did not have the required data i.e. movie.backdrop, director, title etc. - c5806bc8727cd04c1d9c7667111db7338abc73d6

**Comment by seanf316** [comment]
Added a close button to the Trailer model based off user feedback - db84c67ac863c82f3a22f23ae56e1892c316be9f

**Comment by seanf316** [comment]
Fixed issue with Director not showing outside of mobile screen - 688f9db64603fa045e04c6e5dfd11293be1ed5c9

**Comment by seanf316** [comment]
Moviedetails template updated with review code references - a13fafa541eef2680cfd8abae490aec6e371f0fa

**Comment by seanf316** [comment]
Movie details template - edit button updated with the link to the edit_review view - 42d02b9f5d9744c57ca216fc0a091254b3e9fef0

**Comment by seanf316** [comment]
Movie details template updated to specify user review for review button - bcf1cfd8d698a323bdec095aee84660b96e18c92

**Comment by seanf316** [comment]
Template updated to fix flex issue around buttons - ed2184f8358d79c2b65c0a6ae6c3009bf8354b7d

**Comment by seanf316** [comment]
rating_avg added to moviedetails template, reviews removed and placed in allreviews - 8dc7c4f15cdbe5cd746e7fcc22c38ffeb26bb898
