### ISSUE TITLE
USER STORY: User Review

### ISSUE THREAD

**Issue by seanf316** [seanf316/P4-Cinema-Go#25]
As a **User** I want **the ability to review Movies** so that **I can share my thoughts of the Movie with family and friends**

## Acceptance Criteria
- Registered Users would have the ability to review Movies they have selected to review
- Users that are not registered will be alerted to sign-up to Review

## Tasks
- [x] Task 1 - Create Review App
- [x] Task 2 - Create Review Model
- [x] Task 3 - Create view code

**Comment by seanf316** [comment]
Review app created and INSTALLED APPS updated in cinemago settings.py - 304a3e985dcdf7e368122a3b42d265c1242bc3d3

**Comment by seanf316** [comment]
Review model created and migrated - 57a7849d164376049aa354cad3729fd04e40a816

**Comment by seanf316** [comment]
Review view created - 0c56ff502d4f1b32b99600a42d5d3bab9832a332

**Comment by seanf316** [comment]
Review urls updated with review path - 83cf9b484e6e8690ca1b53952f63c132ed793296

**Comment by seanf316** [comment]
Review form created - 3faa9d885e55dbd110742022152358634020b5bd

**Comment by seanf316** [comment]
Review model updated with Richtextfield - ed41c6e89004fb7c1539a17c84a09a3acb24fd22

**Comment by seanf316** [comment]
Movie views updated with view for profile reviewed movie list - e0b35568e222b2fef168c5dbc59cd38ce2378a77

**Comment by seanf316** [comment]
Movie urls was updated with profile reviewed movie list view path - fbaa4d14ff97d4e78bf5db9e76295d5ece93c354

**Comment by seanf316** [comment]
Changed the reverse path for the delete review view - e9fa524941abe4e94d97985971f42abecbb1b80a

**Comment by seanf316** [comment]
Change reverse path for review creation to allreviews - 43ea0216e28f78898fd78f3d91f5ca863718dccb

**Comment by seanf316** [comment]
Max Length Validator added to Review about field, label also updated to indicate Max Characters - 0080d0af21b35b17650528aaed99285eeb008ad8

**Comment by seanf316** [comment]
Review rating label changed to indicate rating range - 74078585a7f42f3573fdd4f3e054ad1a0afbc60c

**Comment by seanf316** [comment]
Added missing message to comment and review forms - 430a3221f913b2dee87f342c2087108697a67acc

**Comment by seanf316** [comment]
Review/Comment field updated with default text - c79e127f8a33dadcdb7f0e3ac9bd6123ea297c47
