### ISSUE TITLE
USER STORY: Write README.md

### ISSUE THREAD

**Issue by seanf316** [seanf316/P4-Cinema-Go#33]
Create/Write README.md

## Acceptance Criteria
- Readme available on Github

## Tasks
- [x] Task 1 - Write site overview
- [x] Task 2 - Write Table of Contents
- [x] Task 3 - Write sections for Table of Contents
- [x] Task 4 - Create Gifs/Screenshots of site

**Comment by seanf316** [comment]
Site overview added, UX section has begun and site gif added - 8e865a1690b6af6409576159d70d91ab1aa2e65a

**Comment by seanf316** [comment]
Updated Project Goals and Epics section - 589c1faf8bd5199183304e4abb4ec687296cf251

**Comment by seanf316** [comment]
Skeleton Plane started- 89b75d1c8ad85adece167a333b7b7a231b994158

**Comment by seanf316** [comment]
More updated applied to Skeleton plane in readme - 6cb5966b5cd98040aeac054d86cf0fe85d7e0a04

**Comment by seanf316** [comment]
Scope Plane updated and Features section started in README - 9acdba01f944c730ca3b9c645f98ff430528a60d

**Comment by seanf316** [comment]
Features section completed and Surface Plane added - c6fa81eaabd833312fab4663c87b278422696912

**Comment by seanf316** [comment]
Technologies used section completed - 0a6a7d75036adeee26c56d39b5fa0341441b142d

**Comment by seanf316** [comment]
Credits and Acknowledgements added to README - c6a5630dd608b8f3a761d01cf903dc64cd913865

**Comment by seanf316** [comment]
Spellings and Grammar mistakes fixed - 25abfa154aa4069a464f54e94c043ae5021b6fce

**Comment by seanf316** [comment]
Epics and User Stories updated - 12c5a872bfc462cfd174f42e9a834922274f6d01

**Comment by seanf316** [comment]
Updated with Email verification/Password reference - fa106207df925c2e8cbaaa1fc9cd7aa888e09c7e
