### ISSUE TITLE
USER STORY: Write TESTING.md

### ISSUE THREAD

**Issue by seanf316** [seanf316/P4-Cinema-Go#34]
Create/Write TESTING.md

## Acceptance Criteria
- Testing carried out and updated in TESTING.md

## Tasks
- [x] Task 1 - Complete HTML Validation
- [x] Task 2 - Complete CSS Validation
- [x] Task 3 - Complete JS Validation
- [x] Task 4 - Complete Python Validation
- [x] Task 5 - Provide Unit testing
- [x] Task 6 - Complete Manual Testing
- [x] Task 7 - Create screenshots for TESTING.md

**Comment by seanf316** [comment]
Unit testing done for Movie views and models - 2b6ded11f1a7d50f5fc5ac719d06997fe78e5e69

**Comment by seanf316** [comment]
Unit testing done for Profile views, models and forms - 6840bb0abede65a6f1c06d526c84e3a04ac40c8e

**Comment by seanf316** [comment]
Unit testing done for Review views, models and forms - c98f6cc61ba017312f2ccd03c63c0fcadb3d7c08

**Comment by seanf316** [comment]
Unit testing screenshots added along with Coverage report - 1c012ad4ec8c96e61362f176727b3a2733dd4436

**Comment by seanf316** [comment]
Validation section started in Testing.md - 8ecb6eeef50ee2f2faf29c14b86c7b1e4b02dc2a

**Comment by seanf316** [comment]
Lighthouse section added to TESTING.md - 5afd19b3b443aa06ecec6b4747900fdd856ef7d8

**Comment by seanf316** [comment]
Negative Testing section added to TESTING.md - b7a889dedd6aaac4fafb31d2cbfaed64e39f43b4

**Comment by seanf316** [comment]
User Story Testing & Wave results added - d569188ff1a0bccd67626f6818ee813a0e82bcba

**Comment by seanf316** [comment]
Manual JS testing added to TESTING.md - e0934ffd24be2c0b9d4de62faf9d33e6ea733e06
