### ISSUE TITLE
USER STORY: Trending Movies

### ISSUE THREAD

**Issue by seanf316** [seanf316/P4-Cinema-Go#35]
As a **Developer** I can **build a page to display Trending Movies** so that **the User can see the latest Trending Movies**

## Acceptance Criteria
- When the User selects Trending from the Movies dropdown they will be met with a page that displays the Trending Movies

## Tasks
- [x] Create the Trending Movies page - extend from Base.html
- [x] Style to match site theme
- [x] Update Urls if required

**Comment by seanf316** [comment]
Trending page has been created and urls have been updated. - baeec66ce70c63eec909cba443bf914c96b844bd

Leaving this story In-Progress as more styling will be applied.

**Comment by seanf316** [comment]
Further styling was applied to the Trending/Top Rated/Movie Details in this commit - 6edc5c6231a48a7ed90a1c73641d78de4c4bad36

**Comment by seanf316** [comment]
Updated the pagination for Trending after some user feedback, Prev/Next buttons added to template and view updated - 1ed6254fc14d63ebcb6b79144edfd36f158baee5

**Comment by seanf316** [comment]
Centered the Prev/Next buttons and added icons - 90e8029c33b1eb663f977d311856b8aca8bc184b
