### ISSUE TITLE
USER STORY: Top Rated Movies

### ISSUE THREAD

**Issue by seanf316** [seanf316/P4-Cinema-Go#36]
As a **Developer** I can **build a page to display the Top Rated Movies** so that **the User can easily get access to the Top Rated Movies of all time**

## Acceptance Criteria
- When the User selects Top Rated from the Movies dropdown they will be met with a page that displays the Top Rated Movies

## Tasks
- [x] Task 1 - Create the Top Rated Movies page - extend from Base.html
- [x] Task 2 - Style to match site theme
- [x] Task 3 - Update Urls if required

**Comment by seanf316** [comment]
Top Rated page has been created and urls have been updated. - 8fdc83995c1765a191bc3171364ab76545969899

Leaving this story In-Progress as more styling will be applied.

**Comment by seanf316** [comment]
Further styling was applied to the Trending/Top Rated/Movie Details in this commit - 6edc5c6231a48a7ed90a1c73641d78de4c4bad36

**Comment by seanf316** [comment]
Updated the pagination for Top Rated after some user feedback, Prev/Next buttons added to template and view updated - 1ed6254fc14d63ebcb6b79144edfd36f158baee5

**Comment by seanf316** [comment]
Centered the Prev/Next buttons and added icons - 90e8029c33b1eb663f977d311856b8aca8bc184b

**Comment by seanf316** [comment]
Poster height updated to match Trending - 4b8bb3a88c48567f2e55b749e6b2c506cbe88b41
