### ISSUE TITLE
USER STORY: Movie Search Results Template

### ISSUE THREAD

**Issue by seanf316** [seanf316/P4-Cinema-Go#37]
As a **Developer** I can **create the Movie Search Results template** so that **the User has a clear display of the results from their search**

## Acceptance Criteria
- Create a responsive template that allows the user to quickly display the results from their search

## Tasks
- [x] Task 1 - Create Movie Search Results Template and extend from Base.html
- [x] Task 2 - Style Template to match site theme
- [x] Task 3 - Link in view code
- [x] Task 4 - Add pagination to the view
- [x] Task 5 - Update URL's if required

**Comment by seanf316** [comment]
Movie Search Results Template created and extended from Base.html. It was linked using the view code and urls.py was updated. - 451290ae3f86c27ed96f43bb19af5ee074eeab66

Styling is on-going.

**Comment by seanf316** [comment]
Updated the pagination for Search Results after some user feedback, Prev/Next buttons added to template and view updated - 1ed6254fc14d63ebcb6b79144edfd36f158baee5

**Comment by seanf316** [comment]
Centered the Prev/Next buttons and added icons - 90e8029c33b1eb663f977d311856b8aca8bc184b

**Comment by seanf316** [comment]
Updated the Search Results template with "if" statements for data received from API - 4a246680ab8600f1638ac0622ccb33ffccabfb7c
