### ISSUE TITLE
USER STORY: Movie model

### ISSUE THREAD

**Issue by seanf316** [seanf316/P4-Cinema-Go#38]
As a **Developer** I will **create a Movie model** so that **the movie details that the user references can be saved to the database for use with Reviews/Profile etc**

## Acceptance Criteria
- When the User searches for a movie or chooses one from the Trending/Top Rated the details of this movie will be saved to the database for future reference.

## Tasks
- [x] Task 1 - Plan Model Structure 
- [x] Task 2 - Create the Model
- [x] Task 3 - Register in admins.py

**Comment by seanf316** [comment]
Movie model has been created and registered in the admins.py. Testing completed using the moviedetails view and admin panel reviewed. - 578f33158505b16a7d64757e5c7bca46715e0bb9

**Comment by seanf316** [comment]
Movie model edited to change Director field to blank=True - b5fa99ed1baac21b27ec9ae5f4de5762194a18c0

**Comment by seanf316** [comment]
Movie model fields edited to include null=True - 85ca025f456392503515c29a816660ef6e020124
