### ISSUE TITLE
USER STORY: Edit Profile Template

### ISSUE THREAD

**Issue by seanf316** [seanf316/P4-Cinema-Go#40]
As a **Developer** I can **create an edit Profile template** so that **the User has a nice display for when they want to update their Profile**

## Acceptance Criteria
- User selects Edit on Profile template and Edit Profile template is rendered.

## Tasks
- [x] Task 1 - Create the Edit Profile Page - extend from Base.html
- [x] Task 2 - Style the page to match site theme
- [x] Task 3 - Write the view code
- [x] Task 4 - Update urls
- [x] Task 5 - Add "CTA" Buttons to allow for CRUD functionality i.e. Update

**Comment by seanf316** [comment]
Profile form created - e269a6a22a2266507ce086631e3b21cdf75e657a

edit_profile view created - 4a548be299f0d69290c734d099b358d3d7938627

profile urls updated - a3f70d56bea33ed46cbe024174e2ca221fd85ddd

Edit Profile template created and styled - 2fdb96e1d2ce38360b572fb36c469f07de8d2c5e

**Comment by seanf316** [comment]
I had to change the version of crispy forms that I was using due to an issue with Bootstrap 5 crispy templates where the current profile image url was not displaying - ea03e36d3486a88a49ff83af8a07f6fa5bcdb8a0

Summernote config was added to settings.py too so I could resize the editor in the Profile form and customize the toolbar - c96cd2e8d920cbd825c8498e6df29a1d874016c0

**Comment by seanf316** [comment]
Fixed overflow scroll issue with default image name - 72bf525c256ac2edfd1cc25be3a5d5a76d155d7f
