### ISSUE TITLE
USER STORY: Delete Profile

### ISSUE THREAD

**Issue by seanf316** [seanf316/P4-Cinema-Go#41]
As a **Developer** I can **create a Delete Profile view** so that **the User has access to delete their account.**

## Acceptance Criteria
- User clicks Delete button in Edit Profile template and will be met with the Delete Profile form.

## Tasks
- [x] Task 1 - Create Delete Profile view code
- [x] Task 2 - Update urls
- [x] Task 3 - Add form html code to Edit Profile template
- [x] Task 4 - Style code to match site theme

**Comment by seanf316** [comment]
Delete profile view code created - 1f61f37dedecd455e18b4da09e437a75983ad832

Profile urls.py updated with new view path - 8c2614968097d3bd4a4e8611dd51ea9ba42d9b5a

Edit Profile template updated with Delete form html code - de75558dc9bedb7dd2e60575ad639b11b7847d3e

Delete Profile section has been styled to match site theme - a03065369e6035fdd7df84330def35dae72f1e01
