### ISSUE TITLE
USER STORY: User Watchlist

### ISSUE THREAD

**Issue by seanf316** [seanf316/P4-Cinema-Go#42]
As a **User** I would **like the ability to add Movies to a watchlist** so that **I can have a list of movies that I can refer to when looking for something to watch**

## Acceptance Criteria
- User can search for movies and add them to a list for watching later

## Tasks
- [x] Task 1 - Build view code
- [x] Task 2 - Update url's
- [x] Task 3 - Update html template where required

**Comment by seanf316** [comment]
Movie views updated with watchlist & prof_watch view code. Also moviedetails view updated to work with new views - f7f54e652c1ee2d92aebfdb1f79ccadc063aa7a0

**Comment by seanf316** [comment]
Movie urls.py updated with the new view paths - c15aef877002173fc56c81f9af41cb9d4ac15f04

**Comment by seanf316** [comment]
Movie Details template was updated with the code for the watchlist view - d593760514933d38b68c1e149aaa917a5e4d8bd1

Profile template was updated with the code for the watchlist view - 5f2ea456778a2f36b6914ce253f4791d25f6527f
