### ISSUE TITLE
USER STORY: All Reviews

### ISSUE THREAD

**Issue by seanf316** [seanf316/P4-Cinema-Go#45]
As a **User** I would **like the ability to view all movie reviews** so that **I can see what my fellow reviewers think of other movies**

## Acceptance Criteria
- User selects the Reviews link in Nav and all Movie Reviews are displayed to user

## Tasks
- [x] Task 1 - Create All Reviews view 
- [x] Task 2 - Update Review urls
- [x] Task 3 - Update code in allreviews.html

**Comment by seanf316** [comment]
allreviews view created - b570890294368ba5a6fdd72fb01a09decaafe97f

**Comment by seanf316** [comment]
Review urls updated with allreviews path - 9888109d3b3620d6ad8cc3df9740eb739a7a7848

**Comment by seanf316** [comment]
allreviews.html updated with view code - 964812350dc7d07a63fb5db31ad1b5fa4e138ef3
