### ISSUE TITLE
USER STORY: All Reviews Template

### ISSUE THREAD

**Issue by seanf316** [seanf316/P4-Cinema-Go#46]
As a **Developer** I can **create an All Reviews page** so that **the User can have a nice display containing all reviews**

## Acceptance Criteria
- Page created that contains all the reviews from the Movie site

## Tasks
- [x] Task 1 - Create All Reviews Template
- [x] Task 2 - Style Template to match site theme
- [x] Task 3 - Link in view code

**Comment by seanf316** [comment]
All Reviews Template created and styled inline with site theme - 964812350dc7d07a63fb5db31ad1b5fa4e138ef3

**Comment by seanf316** [comment]
Updated the template code for Tablet display - 0e99ce43869a45cf3f86481fe67b26dde9527068

**Comment by seanf316** [comment]
Added review.js to reset scroll when mouse leaves card - dea1dce249180d8c390f68f765ab5378ac0971dd

**Comment by seanf316** [comment]
Reviewer profile img/username linked back to the reviewers profile - cb4dc6788e31ed342deeafe9586d40b87de2b0d2

**Comment by seanf316** [comment]
allreviews.html updated with comments references - 859b63790b294195133c9e7c603492eb0cef6ddf

**Comment by seanf316** [comment]
allreviews.html updated with edit comment references - 85d22d66b54221a25bb335d98f92e3c086e05102

**Comment by seanf316** [comment]
allreviews.html updated with delete comment references - 04fb14d76f13b6265c4b98ac46a95b25e9523bc1

**Comment by seanf316** [comment]
Put some extra padding on review card based on user feedback - b36627954baeee33e43e8f0dd3eb6434310a9e68
