### ISSUE TITLE
USER STORY: Email Verification & Password Reset

### ISSUE THREAD

**Issue by seanf316** [seanf316/P4-Cinema-Go#47]
As a **Developer** I can **add functionality to verify email and reset password** so that **the user has better security over their email being used and can reset password if they forget it**

## Acceptance Criteria
- Users are able verify their email when signing up
- Registered Users are able to reset password if they forgot it

## Tasks
- [x] Task 1 - Update allauth email settings in settings.py
- [x] Task 2 - Update site name in Django admin view
- [x] Task 3 - Store private email keys in env.py
- [x] Task 4 - Style templates

**Comment by seanf316** [comment]
Email verification & Password reset added - f607aac58bb200007f1156fc9262da4397759c9e

**Comment by seanf316** [comment]
Comment incorrectly placed in this User Story - moved to README User Story
